NAME = "self-explanatory"
RACE = "what species your character is"
HUMAN = "Do I even have to explain that?"
DWARF = "sturdy and honest, this short folk of the mountains are master craftsmen"
ELF = "selfish and speaking in riddles, the noble protectors of the forests roam the wild"
HALFLING = ""
DRAGONBORN = "clad in an armor of draconic scales, you bring doom to your foes with your elemental breath"
GNOME = "nimble and full of trickery, you are the shortest of all, always tinkering around"
HALF_ELF = ""
HALF_ORC = "with the raw strength from your orc'ish heritage you plow through enemy forces"
TIEFLING = "with a demonic ancestor you have hellish blood pumping trough your veins"


CLASS = "determines how your character will fight, if they are a spellcaster or a martial fighter (or a bit of both)"
BARBARIAN = "With brutal strength you crush your enemies bones and strike with restless rage"
BARD = "as a magical musician you cast spells through songs and melodies, weakening your foes and empowering your allies"
CLERIC = "a priest/ess of a divine diety, you harness its might to empower your spells"
DRUID = "speaking with animals and plants, you terrorize your foes with the magical wrath of nature"
FIGHTER = "as a master of combat you can wield several different types of weapons"
MONK = "as a martial artist you shine in hand-to-hand- and close-quarter-combat and seek out spiritual and physical perfection"
PALADIN = "as a holy warrior bound to your oath you smite your opponents with radiant light"
RANGER = "as a hunter in the woods you strike from afar, prowling the wilds"
ROGUE = "cunning and sneaky, you strike from the shadows and take what you want"
SORCERER = "magically gifted through draconic blood o otherwise, you reach havoc or try to help the poor"
WARLOCK = "having struck a pact with an elder being, you make others fear you trough your pact magic"
WIZARD = "as a magical scholar you cast spells from your evergrowing repertoire of destructive energy"


STATS = "How good you are at something in general"
MODIFIER = "numbers calculated from your stats, important for rolling dice and stuff"


STR = "Strength measures bodily power, athletic training, and the extent to which you can exert raw physical force"
STR_TOM = "How far and hard you can throw a tomato"
DEX = "Dexterity measures agility, reflexes, and balance"
DEX_TOM = "how precise you can throw a tomato or how well you can dodge one"
CON = "Constitution measures health, stamina, and vital force"
CON_TOM = "how rotten a tomato can be for you to still be able to eat it"
INT = "Intelligence measures mental acuity, accuracy of recall, and the ability to reason"
INT_TOM = "knowing that a tomato is a fruit"
WIS = "Wisdom reflects how attuned you are to the world around you and represents perceptiveness and intuition"
WIS_TOM = "knowing that a tomato doesn't belong in a fruit salad"
CHA = "Charisma measures your ability to interact effectively with others. It includes such factors as confidenceand eloquence, and it can represent a charming or commanding personality"
CHA_TOM = "being able to sell a tomato-based fruit salad"
